### ISSUE TITLE
Expose navigator.clipboard in happ window

### ISSUE THREAD

**Issue by mattyg** [holochain/launcher#192]
I want to be able to write to the clipboard in my app. It seems like I should be able to use `navigator.clipboard.writeText()` (this works fine in a demo electron app), but in the happ window `navigator.clipboard` is undefined.

Also it looks like navigator.clipboard works fine when the happ is run via hc-spin

**Comment by matthme** [comment]
fixed with #195 and will be released in 0.300.2
