### ISSUE TITLE
MacOS updating throws an error

### ISSUE THREAD

**Issue by snowshiva** [holochain/launcher#194]
tested on macOS Sonoma 14.1.1 (arm)

**Comment by snowshiva** [comment]
![Image](https://github.com/user-attachments/assets/c6533158-6440-4d6d-a013-7e16105eba26)

**Comment by snowshiva** [comment]
@matthme I think this is complete, it is from my pov anyway

**Comment by matthme** [comment]
Great! Will close it then.
